#server:
#  port: 8081
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
#spring:
#  application:
#    name: grpc-client

server:
  port: 8081

spring:
  application:
    name: grpc-client
  boot:
    admin:
      client:
        url: http://localhost:8080
# Enable logging
logging:
  level:
    root: INFO
    com.deft: INFO

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    health:
#      show-details: always